// <auto-generated />
namespace GaoKao.WebUI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addtestcreatetimes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtestcreatetimes));
        
        string IMigrationMetadata.Id
        {
            get { return "201503171535553_addtestcreatetimes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
