// <auto-generated />
namespace GaoKao.WebUI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addquestionpaper : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addquestionpaper));
        
        string IMigrationMetadata.Id
        {
            get { return "201502061436018_addquestionpaper"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
