// <auto-generated />
namespace GaoKao.WebUI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addquestionitem1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addquestionitem1));
        
        string IMigrationMetadata.Id
        {
            get { return "201503161427133_addquestionitem1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
