// <auto-generated />
namespace GaoKao.WebUI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addmydictionarygrouptimesss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmydictionarygrouptimesss));
        
        string IMigrationMetadata.Id
        {
            get { return "201503171528455_addmydictionarygrouptimesss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
