// <auto-generated />
namespace GaoKao.WebUI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addmodifitime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addmodifitime));
        
        string IMigrationMetadata.Id
        {
            get { return "201503181452090_addmodifitime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
